import dotenv from 'dotenv';
import { connectDB } from '../config/database';
import { Product } from '../models/Product';

dotenv.config();

async function run() {
  await connectDB();
  console.log('Seeding products...');

  const sample = [
    {
      name: 'Classic Linen Shirt',
      slug: 'classic-linen-shirt',
      description: 'Breathable linen shirt perfect for summer days.',
      price: 1999,
      salePrice: 1799,
      images: [
        { url: 'https://picsum.photos/seed/linen1/600/800', alt: 'Linen shirt front' },
        { url: 'https://picsum.photos/seed/linen2/600/800', alt: 'Linen shirt back' }
      ],
      category: 'Tops',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [ { name: 'Beige', hex: '#F5F5DC' }, { name: 'White', hex: '#FFFFFF' }],
      stock: 50,
      brand: 'Niraya Studio',
      isNewProduct: true,
      isBestseller: false,
      material: '100% Linen',
    },
    {
      name: 'High-Rise Wide Pants',
      slug: 'high-rise-wide-pants',
      description: 'Comfortable wide-leg pants with a flattering fit.',
      price: 2499,
      images: [ { url: 'https://picsum.photos/seed/pants1/600/800', alt: 'Wide pants' } ],
      category: 'Bottoms',
      sizes: ['XS', 'S', 'M', 'L'],
      colors: [ { name: 'Black', hex: '#000000' } ],
      stock: 35,
      brand: 'Niraya Essentials',
      isNewProduct: true,
      isBestseller: true,
      material: 'Cotton Blend',
    },
    {
      name: 'Oversized Cotton Tee',
      slug: 'oversized-cotton-tee',
      description: 'Soft 180 GSM cotton tee with an oversized silhouette.',
      price: 999,
      images: [ { url: 'https://picsum.photos/seed/tshirt1/600/800', alt: 'Oversized tee' } ],
      category: 'Tops',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: [ { name: 'White', hex: '#FFFFFF' }, { name: 'Navy', hex: '#1F2A44' } ],
      stock: 120,
      brand: 'Niraya Basics',
      isNewProduct: false,
      isBestseller: true,
      material: '100% Cotton',
    },
    {
      name: 'Tailored Blazer',
      slug: 'tailored-blazer',
      description: 'Single-breasted blazer with notch lapel and structured shoulders.',
      price: 4999,
      images: [ { url: 'https://picsum.photos/seed/blazer1/600/800', alt: 'Blazer' } ],
      category: 'Outerwear',
      sizes: ['S', 'M', 'L'],
      colors: [ { name: 'Charcoal', hex: '#36454F' } ],
      stock: 18,
      brand: 'Niraya Atelier',
      isNewProduct: true,
      isBestseller: false,
      material: 'Poly-viscose blend',
    },
    {
      name: 'A-Line Midi Dress',
      slug: 'a-line-midi-dress',
      description: 'Flowy midi dress with a flattering A-line cut and waist tie.',
      price: 2799,
      images: [ { url: 'https://picsum.photos/seed/dress1/600/800', alt: 'Midi dress' } ],
      category: 'Dresses',
      sizes: ['XS', 'S', 'M', 'L'],
      colors: [ { name: 'Sage', hex: '#9CAF88' }, { name: 'Black', hex: '#000000' } ],
      stock: 42,
      brand: 'Niraya Studio',
      isNewProduct: false,
      isBestseller: true,
      material: 'Rayon',
    },
    {
      name: 'Cable Knit Sweater',
      slug: 'cable-knit-sweater',
      description: 'Chunky cable knit sweater for cozy evenings.',
      price: 2299,
      images: [ { url: 'https://picsum.photos/seed/knit1/600/800', alt: 'Knit sweater' } ],
      category: 'Knitwear',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [ { name: 'Oatmeal', hex: '#E6D8C3' } ],
      stock: 28,
      brand: 'Niraya Cozy',
      isNewProduct: false,
      isBestseller: false,
      material: 'Wool Blend',
    },
    {
      name: 'Denim Trucker Jacket',
      slug: 'denim-trucker-jacket',
      description: 'Heritage fit denim jacket with light stonewash.',
      price: 3499,
      images: [ { url: 'https://picsum.photos/seed/denim1/600/800', alt: 'Denim jacket' } ],
      category: 'Outerwear',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [ { name: 'Light Blue', hex: '#87A9C4' } ],
      stock: 24,
      brand: 'Niraya Denim',
      isNewProduct: false,
      isBestseller: true,
      material: '100% Cotton Denim',
    },
    {
      name: 'Pleated Midi Skirt',
      slug: 'pleated-midi-skirt',
      description: 'Lightweight pleated skirt with elastic waistband.',
      price: 1899,
      images: [ { url: 'https://picsum.photos/seed/skirt1/600/800', alt: 'Pleated skirt' } ],
      category: 'Bottoms',
      sizes: ['XS', 'S', 'M', 'L'],
      colors: [ { name: 'Blush', hex: '#F2C1C1' } ],
      stock: 37,
      brand: 'Niraya Studio',
      isNewProduct: true,
      isBestseller: false,
      material: 'Polyester',
    },
    {
      name: 'Chino Shorts',
      slug: 'chino-shorts',
      description: 'Straight-fit chino shorts with 7-inch inseam.',
      price: 1299,
      images: [ { url: 'https://picsum.photos/seed/shorts1/600/800', alt: 'Chino shorts' } ],
      category: 'Bottoms',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [ { name: 'Khaki', hex: '#C3B091' }, { name: 'Navy', hex: '#1F2A44' } ],
      stock: 60,
      brand: 'Niraya Essentials',
      isNewProduct: false,
      isBestseller: false,
      material: 'Cotton Twill',
    },
    {
      name: 'Merino Crew Sweater',
      slug: 'merino-crew-sweater',
      description: 'Fine-gauge merino wool sweater with a classic crew neck.',
      price: 2999,
      images: [ { url: 'https://picsum.photos/seed/merino1/600/800', alt: 'Merino sweater' } ],
      category: 'Knitwear',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: [ { name: 'Forest', hex: '#228B22' } ],
      stock: 22,
      brand: 'Niraya Luxe',
      isNewProduct: false,
      isBestseller: true,
      material: '100% Merino Wool',
    },
    {
      name: 'Trench Coat',
      slug: 'classic-trench-coat',
      description: 'Water-resistant trench with removable belt and storm flap.',
      price: 5999,
      images: [ { url: 'https://picsum.photos/seed/trench1/600/800', alt: 'Trench coat' } ],
      category: 'Outerwear',
      sizes: ['S', 'M', 'L'],
      colors: [ { name: 'Sand', hex: '#C2B280' } ],
      stock: 12,
      brand: 'Niraya Atelier',
      isNewProduct: true,
      isBestseller: false,
      material: 'Cotton-Poly Blend',
    },
    {
      name: 'Ribbed Tank Top',
      slug: 'ribbed-tank-top',
      description: 'Stretch ribbed tank, perfect for layering.',
      price: 699,
      images: [ { url: 'https://picsum.photos/seed/tank1/600/800', alt: 'Ribbed tank' } ],
      category: 'Tops',
      sizes: ['XS', 'S', 'M', 'L'],
      colors: [ { name: 'Black', hex: '#000000' }, { name: 'Ivory', hex: '#FFFFF0' } ],
      stock: 85,
      brand: 'Niraya Basics',
      isNewProduct: false,
      isBestseller: true,
      material: 'Cotton-Spandex',
    },
    {
      name: 'Wool Blend Overcoat',
      slug: 'wool-blend-overcoat',
      description: 'Minimal overcoat with clean lines and concealed buttons.',
      price: 6499,
      images: [ { url: 'https://picsum.photos/seed/overcoat1/600/800', alt: 'Overcoat' } ],
      category: 'Outerwear',
      sizes: ['M', 'L', 'XL'],
      colors: [ { name: 'Camel', hex: '#C19A6B' } ],
      stock: 10,
      brand: 'Niraya Luxe',
      isNewProduct: false,
      isBestseller: true,
      material: 'Wool Blend',
    },
  ];

  await Product.deleteMany({ slug: { $in: sample.map(s => s.slug) } });
  await Product.insertMany(sample);

  console.log('✅ Seed completed.');
  process.exit(0);
}

run().catch(err => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
